config/routes.rb
Rails.application.routes.draw do

  devise_for :books
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :books, only: [:index, :show] do
  	resources :posts
  end

  authenticated :book do
  	root 'books#dashboard', as: 'authenticated_root'
  end
  
  root 'welcome#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts

  has_attached_file :book_thumbnail, styles: { large: "1000*1000>", medium: "500*500>" }
  validates_attachment_content_type :book_thumbnail, content_type: /\Aimage\/.*\Z/
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :book


  has_attached_file :thumbnail, styles: { large: "1000*1000>", medium: "500*500>" }
  validates_attachment_content_type :thumbnail, content_type: /\Aimage\/.*\Z/

  has_attached_file :mp3
  validates_attachment :mp3, :content_type => { :content_type => ["audio/mpeg", "audio/mp3"] }, :file_name => { :matches => [/mp3\Z/] }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.permit(:sign_up) {
  		|u| u.permit(:email, :password, :password_confirmation, :title, :book_thumbnail )
  	}
  	devise_parameter_sanitizer.permit(:account_update) {
  		|u| u.permit(:email, :password, :password_confirmation, :current_password,
  					:title, :book_thumbnail, :description )
  	}
  end
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :find_book, only: [:show, :dashboard]
	before_action :find_post, only: [:show, :dashboard]

	def index
		@books = Book.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 9)
	end

	def show
	end

	def dashboard	
	end

	private

	def find_post
		@posts = Post.where(book_id: @book).order(:id).paginate(:page => params[:page], :per_page => 6)
	end

	def find_book
		if params[:id].nil?
			@book = current_book
		else
			@book = Book.find(params[:id])
		end
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_book!
	before_action :require_permission, except: [:show]
	before_action :find_book
	before_action :find_post, only: [:show, :edit, :update, :destroy]

	def new
		@post = @book.posts.new
	end

	def create
		@post = @book.posts.new(post_params)
		if @post.save
			redirect_to root_path
		else
			render 'new'
		end
	end
 
	def show
		@posts = Post.where(book_id: @book).order(:id).paginate(:page => params[:page], :per_page => 1)
	end

	def edit
		
	end

	def update
		if @post.update post_params
			redirect_to book_post_path(@book, @post), notice: "post was succesfully updated!"
		else
			render 'edit'
		end
	end

	def destroy
		@post.destroy
		redirect_to root_path
	end

private

	def post_params
		params.require(:post).permit(:description, :thumbnail, :id, :mp3)
	end

	def find_book
		@book = Book.find(params[:book_id])
	end

	def find_post
		@post = Post.find(params[:id])
	end

	def require_permission
		@book =Book.find(params[:book_id])
		if current_book != @book
			redirect_to root_path, notice: "Sorry, you're not allow to view that post."
		end
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
	FLASH_CLASSES ={ alert: "danger", notice: "success", warning: "warning" }.freeze

	def flash_class(key)
		FLASH_CLASSES.fetch key.to_sym, key
	end

	def user_facing_flashes
		flash.to_hash.slice "alert", "notice", "warning"
	end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/books/dashboard.html.erb
<div id="book_show">
	<div id="show_banner">
		<div class="wrapper_skinny">
			<h1><%= @book.title %></h1>
		</div>
	</div>

	<div id="links">
		<div class="wrapper_skinny">
			<ul>
				<li class="current">Pages</li>
				<li><%= link_to "Add New post", new_book_post_path(@book) %></li>
				<li><%= link_to "Book Settings", edit_book_registration_path %></li>
				<li><%= link_to "View Books", books_path %></li>
			</ul>
		</div>
	</div>

	<div id="posts">
		<div class="wrapper_skinny">
			<ul class="cf">
				<% @posts.each do |post| %>
					<li class="cf">
						<div class="post_thumbnail">
							<a href="#">
								<%= image_tag post.thumbnail.url(:large) %>
							</a>
						</div>
						<div class="post_overview">
							<h2><%= link_to post.description, book_post_path(@book, post) %></h2>
							<p>post No. <%= post.id %></p>
							<div class="authorized_links">
								<%= link_to "Edit", edit_book_post_path(@book, post) %>
								<%= link_to "Delete", book_post_path(@book, post), method: :delete, data: {confirm: "Are you sure?"} %>
							</div>
						</div>
					</li>
				<% end %>
			</ul>
		</div>
	</div>
</div>
<%= will_paginate @posts, previous_label: "上一页", next_label: "下一页" %>

app/views/books/index.html.erb
<div id="banner" class="books_banner">
	<h1>目录</h1>
</div>

<div id="books" class="cf">
	<div class="wrapper">
		<ul class="cf">
			<% @books.each do |book| %>
				<%= link_to book do %>
					<li>
						<%= image_tag book.book_thumbnail.url(:medium) %>
						<div class="book_overview">
							<h2><%= book.title %></h2>
							<p class="page_count">1 page</p>
						</div>
					</li>
				<% end %>
			<% end %>
		</ul>
		<%= will_paginate @books, previous_label: "上一页", next_label: "下一页" %>
	</div>
</div>

app/views/books/show.html.erb
<div id="book_show">
	<div id="show_banner">
		<div class="wrapper_skinny">
			<h1><%= @book.title %></h1>
			<p class="description"><%= @book.description %></p>
		</div>
	</div>

	<div id="breadcrumb">
		<%= link_to books_path do %>
			All Books
			<span>/</span>
			Test
		<% end %>
	</div>

	<div id="posts">
		<div class="wrapper_skinny">
			<ul class="cf">
				<% @posts.each do |post| %>
					<li class="cf">
						<div class="post_thumbnail">
							<%= link_to image_tag(post.thumbnail.url(:medium)), book_post_path(@book, post) %>
							<div class="post_overview">
								<p class="description"><%=link_to post.description, book_post_path(@book, post) %></p>
							</div>
						</div>
					</li>
				<% end %>
			</ul>
		</div>
	</div>
</div>

		<%= will_paginate @posts, previous_label: "上一页", next_label: "下一页" %>

app/views/common/_flashes.html.erb
<% if flash.any? %>
	<% user_facing_flashes.each do |key, value| %>
		<div class="alert alert-dismissable alert-<%= flash_class(key) %>">
			<button class="close" data-dismiss="alert">x</button>
			<%= value %>
		</div>
	<% end %>
<% end %>

app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
	<p class="text-center">Copyright 2017 USA English
		<br>Design by Chenxing
		
	</p>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
	<div class="container-fluid">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<a class="navbar-brand" href="/">USA English</a>
		</div>

		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav navbar-right">
				<% unless book_signed_in? %>
					<li><%= link_to "发现", books_path %></li>
					<li><%= link_to("注册书籍", new_book_registration_path ) %></li>
					<li><%= link_to("登录书籍", new_book_session_path ) %></li>
				<% else %>
					<li><%= link_to "发现", books_path %></li>
					<li><%= link_to "Dashboard", root_path %></li>
					<li><%= link_to "登出", destroy_book_session_path, method: :delete %></li>
				<% end %>
			</ul>
		</div>
		<!-- /.navbar-collapse -->
	</div>
	<!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Book Reading</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  	<div class="container-fluid">
  		<%= render "common/navbar" %>
      <%= render "common/flashes" %>
	    <%= yield %>
  	</div>

  	<%= render "common/footer" %>
  	
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for ([@book, @post]) do |f| %>

	<div class="field">
		<%= f.label :picture %><br>
		<%= f.file_field :thumbnail %>
	</div>

	<div class="field">
		<%= f.label :page_number %><br>
		<%= f.text_field :id %>
	</div>

	<div class="field">
		<%= f.label :description %><br>
		<%= f.text_area :description %>
	</div>

	<div class="field">
		<%= f.label :mp3 %><br>
		<%= f.file_field :mp3 %>
	</div>

	<%= f.submit class: "button button_highlight button_block" %>
<% end %>

app/views/posts/edit.html.erb
<div id="book_show">
	<div id="show_banner">
		<div class="wrapper_skinny">
			<h1><%= @book.title %></h1>
		</div>
	</div>

	<div id="links">
		<div class="wrapper_skinny">
			<ul>
				<li><%= link_to "Pages", root_path %></li>
				<li><%= link_to "Add New Page", new_book_post_path(@book) %></li>
				<li><%= link_to "Book Settings", edit_book_registration_path %></li>
				<li><%= link_to "View Books", books_path %></li>
			</ul>
		</div>
	</div>

	<div id="form">
		<div class="wrapper_skinny">
			<%= render 'form' %>
		</div>
	</div>
</div>

app/views/posts/new.html.erb
<div id="book_show">
	<div id="show_banner">
		<div class="wrapper_skinny">
			<h1><%= @book.title %></h1>
		</div>
	</div>

	<div id="links">
		<div class="wrapper_skinny">
			<ul>
				<li><%= link_to "Pages", root_path %></li>
				<li class="current" >Add New Page</li>
				<li><%= link_to "Book Settings", edit_book_registration_path %></li>
				<li><%= link_to "View Books", books_path %></li>
			</ul>
		</div>
	</div>

	<div id="form">
		<div class="wrapper_skinny">
<%= form_for ([@book, @post]) do |f| %>

	<div class="field">
		<%= f.label :picture %><br>
		<%= f.file_field :thumbnail %>
	</div>

	<div class="field">
		<%= f.label :description %><br>
		<%= f.text_area :description %>
	</div>

	<div class="field">
		<%= f.label :mp3 %><br>
		<%= f.file_field :mp3 %>
	</div>

	<%= f.submit class: "button button_highlight button_block" %>
<% end %>		</div>
	</div>
</div>

app/views/posts/show.html.erb
<div id="book_show">
	<div id="breadcrumb">
		<%= link_to book_path do %>
			All Books
			<span>/</span>
			<%= link_to @book.title, book_path(@book) %>
			<span>/</span>
			<%= link_to @post.id %>
		<% end %>
	</div>
	<div id="post_content">
		<div class="wrapper_wide">
			<%= image_tag @post.thumbnail.url(:large) %>
			<h2><%= @post.description %></h2>
			<div id="jquery_jplayer_1" class="jp-jplayer"></div>
	      	<div id="jp_container_1" class="jp-audio">
	        	<div class="jp-type-single">
	         		<div class="jp-gui jp-interface">
	            		<ul class="jp-controls">
			            	<li><a href="javascript:;" class="jp-play" tabindex="1">&#61515;</a></li>
			            	<li><a href="javascript:;" class="jp-pause" tabindex="1">&#61516;</a></li>
			            	<li><a href="javascript:;" class="jp-mute" tabindex="1" title="mute">&#61480;</a></li>
			            	<li><a href="javascript:;" class="jp-unmute" tabindex="1" title="unmute">&#61478;</a></li>
	            		</ul>
	            		<div class="jp-progress">
	            			<div class="jp-seek-bar">
	                			<div class="jp-play-bar"></div>
	              			</div>
	            		</div>
	            		<div class="jp-time-holder">
	            			<div class="jp-current-time"></div>
	            		</div>
	            		<div class="jp-volume-bar">
	            			<div class="jp-volume-bar-value"></div>
	            		</div>
	            		<div class="jp-no-solution">
	              			<span>Update Required</span>
	              			To play the media you will need to either update your browser to a recent version or update your <a href="http://get.adobe.com/flashplayer/" target="_blank">Flash plugin</a>.
	            		</div>
	        		</div>
	        	</div>
	    	</div>
	    </div>
	</div>
</div>


<script>
	$(document).ready(function(){
	  $("#jquery_jplayer_1").jPlayer({
	    ready: function () {
	      $(this).jPlayer("setMedia", {
	        mp3: "<%= @post.mp3.url %>",
	      }).jPlayer("play");
	    },
	    swfPath: "/js",
	    supplied: "mp3"
	  });
	});
</script>

app/views/welcome/index.html.erb
<div id="background">
	<div class="wrapper_skinny">
		<h1>阅读你的第一个英文故事！</h1>
	</div>
</div>